### ISSUE TITLE
Problems with Tensorflow

### ISSUE THREAD

**Issue by JohnV7** [blei-lab/edward#435]
Hi all,
I downgraded tensorflow to 0.11.0 to deal with [issue 315](https://github.com/blei-lab/edward/issues/315).

Now I got this error message

> AttributeError: type object 'GraphKeys' has no attribute 'GLOBAL_VARIABLES'

probably related to tensorflow [issue 742](https://github.com/tensorflow/models/issues/742)

It seems I can neither use tensorflow 0.11.0 nor 0.12.0. Any ideas?

**Comment by pwl** [comment]
Current version (tag [1.2.1](https://github.com/blei-lab/edward/tree/1.2.1)) works with TF 1.0rc0, so you could try that.

**Comment by dustinvtran** [comment]
what @pwl said. when we upgraded to support tensorflow 1.0 in the latest edward version, we subsequently upgraded the syntax in all the example scripts and documentation online.

in the ideal setting, we'd have example scripts and documentation available for each version of edward. at the moment, it's always pointed to the latest version.

**Comment by dustinvtran** [comment]
closing due to incompatible version
